# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address_no', models.CharField(blank=True, max_length=255)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_ward', models.CharField(blank=True, max_length=255)),
                ('address_district', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(default=0)),
                ('birthday', models.DateField(blank=True)),
                ('birtplace', models.CharField(blank=True, max_length=100)),
                ('nation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ID_Student',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.People')),
                ('student_id', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('student.people',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.ID_Student')),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plus', to='class_manage.Class')),
            ],
            options={
                'abstract': False,
            },
            bases=('student.id_student',),
        ),
    ]
