# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('year', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_manage.Term_year'),
        ),
    ]
