# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('class_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Teacher',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.People')),
                ('teacher_id', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('student.people',),
        ),
        migrations.CreateModel(
            name='Work_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_plus', to='class_manage.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.ID_Teacher')),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('teacher.id_teacher',),
        ),
        migrations.AddField(
            model_name='work_assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plus', to='teacher.Teacher'),
        ),
    ]
